config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root to: 'static_pages#top'
  resources :users, only: %i[new create]
  resources :boards do
    resources :comments, shallow: true
    get 'bookmarks', on: :collection
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    post 'logout', to: 'user_sessions#destroy'
    get 'starter', to: 'dashboards#index', as: :root
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :board
  belongs_to :user

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @board = Board.find(params[:board_id])
    @comment = @board.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      # redirect_to board_path(@board), success: t('.success')
    else
      @comments = @board.comments.all.order(created_at: :desc)
      render 'error_create.js.erb'
      # render template: 'boards/show'
    end
  end

  def update
    @comment = current_user.comments.find(params[:id])
    if @comment.update(comment_params)
      render json: @comment
    else
      render 'error_update.js.erb', status: :bad_request
    end
  end

  def destroy
    @comment = current_user.comments.find_by(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<tr id=<%="comment-#{comment.id}"%>>
  <td style="width: 60px">
    <%= image_tag 'sample.jpg', size: '50x50', class: 'rounded-circle' %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.decorate.full_name %></h3>
    <div id="js-comment-<%= comment.id %>">
      <%= simple_format(comment.body) %>
    </div>
    <div style="display: none;" id="js-textarea-comment-box-<%= comment.id %>">
      <textarea class="form-control mb-1" id="js-textarea-comment-<%= comment.id %>"><%= comment.body %></textarea>


    <div id="js-comment-button-<%= comment.id %>" style="desplay: none;">
      <button data-cancel-id=<%= comment.id %> class="btn btn-light comment-cancel-button">キャンセル</button>
      <button data-update-id=<%= comment.id %> class="btn btn-success comment-update-button">更新</button>
    </div>
  </td>
  <% if current_user.own?(comment) %>
    <%= render partial: 'comments/crud_menus', locals: { comment: comment } %>
  <% end %>
</tr>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table id="js-table-comment" class="table">
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/_crud_menus.html.erb
<td class="action">
  <ul class="list-inline justify-content-center" style="float: right;">
    <li class="list-inline-item">

      <a  data-comment-id=<%= comment.id %> class="js-edit-comment-button">
        <i class="fa fa-pen text-primary"></i>
      </a>

    </li>
    <li class="list-inline-item">
      <%= link_to comment_path(comment), class: "js-delete-comment-button", method: :delete, data: { confirm: t('.confirm') }, remote: true do %>
        <%= icon 'fa', 'trash' %>
      <% end %>
    </li>
  </ul>
</td>

app/views/comments/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: [board, comment], url: board_comments_path(board, comment), method: :post, id: 'new_comment', remote: true do |f| %>
    <div id="js-error_messages"></div>
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control mb-3', rows: 4, placeholder: "コメント" %>
      <%= f.submit t('.submit'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$("#js-table-comment").prepend("<%= j(render 'comments/comment', { comment: @comment }) %>");
$("#new_comment textarea").val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/comments/error_ajax.js.erb
$('#js-error_messages').html("<%= j(render 'shared/error_messages', { obj: @comment }) %>");

app/views/comments/error_create.js.erb
$('#js-error_messages').html("<%= j(render 'shared/error_messages', { obj: @comment }) %>");

app/views/comments/error_update.js.erb
$('#js-textarea-comment-box-<%= @comment.id %> .error_messages').remove();
$('#js-textarea-comment-box-<%= @comment.id %>').prepend('<p class="error_messages text-danger">コメントを入力してください</p>');