config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root to: 'static_pages#top'
  resources :users, only: %i[new create]
  resources :boards do
    resources :comments, shallow: true
    get 'bookmarks', on: :collection
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    post 'logout', to: 'user_sessions#destroy'
    get 'starter', to: 'dashboards#index', as: :root
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmark_boards, through: :bookmarks, source: :user
  mount_uploader :board_image, BoardImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[edit update destroy]

  def index
    @q = Board.ransack(params[:q])
    @boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, success: t('.success')
    else
      flash[:danger] = t('.failed')
      render :new
    end
  end

  def show
    @board = Board.find(params[:id])
    @comment = @board.comments.build
    @comments = @board.comments.all.order(created_at: :desc)
  end

  def edit; end

  def update
    board = Board.find(params[:id])
    if board.update(board_params)
      redirect_to board_path(board), success: t('.success')
    else
      flash[:danger] = t('.failed')
      render :edit
    end
  end

  def destroy
    redirect_to boards_path, success: t('.success') if @board.destroy!
  end

  def bookmarks
    @q = current_user.bookmark_boards.ransack(params[:q])
    @bookmark_boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  private

  def board_params
    params.require(:board).permit(:title, :body, :board_image)
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id=<%= "board-id-#{board.id}" %>>
    <div class="card">
      <%= image_tag board.board_image.url, class: 'card-img-top img-fluid', size: '300x200' %>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to board.title, board_path(board) %>
        </h4>
      <ul class="crud-menu-btn list-inline float-right">
        <% if current_user.own?(board) %>
          <%= render partial: 'crud_menus', locals: { board: board } %>
        <% else %>
        <li class='list-inline-item'>
          <%= render partial: 'bookmark_area', locals: { board: board } %>
        </li>
        <% end %>
      </ul>
        <ul class="list-inline">
          <li class="list-inline-item"><%= icon 'far', 'user' %> <%= board.user.decorate.full_name %></li>
          <li class="list-inline-item">
            <%= icon 'far', 'calendar' %>
            <%= l board.created_at, format: :long %>
          </li>
        </ul>
        <p class="card-text"><%= board.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/boards/_bookmark.html.erb
<%= link_to bookmarks_path(board_id: board.id),
            id: "js-bookmark-button-for-board-#{board.id}",
            class: 'float-right',
            method: :post,
            remote: true do %>
  <%= icon 'far', 'star' %>
<% end %>

app/views/boards/_bookmark_area.html.erb
<% if current_user.bookmark?(board)  %>
  <%= render partial: 'unbookmark', locals: { board: board } %>
<% else %>
  <%= render partial: 'bookmark', locals: { board: board } %>
<% end %>

app/views/boards/_crud_menus.html.erb
<li class='list-inline-item'>
  <%= link_to edit_board_path(board), id: "button-edit-#{board.id}" do %>
    <%= icon 'fa', 'pen' %>
  <% end %>
</li>
<li class='list-inline-item'>
  <%= link_to board_path(board), id: "button-delete-#{board.id}", method: :delete, data: {confirm: t('.confim_delete')} do %>
    <%= icon 'fas', 'trash' %>
  <% end %>
</li>

app/views/boards/_form.html.erb
<% content_for(:title, t('.title')) %>
<%= form_with model: @board, local: true do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h1><%= t('.title') %></h1>
        <%= render partial: 'shared/error_messages', locals: { obj: @board} %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: 10 %>
        </div>
        <div class="form-group">
          <%= f.label :board_image, for: :img %>
          <%= f.file_field :board_image, id: :img, accept: "image/jpg,image/gif,image/jpeg,image/png" %>
        </div>
        <div class="form-group">
          <%= image_tag @board.board_image.url, id: :img_prev, size: '300x200' %>
        </div>
        <%= f.submit submit_button, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/boards/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :title_or_body_cont, class: 'form-control', placeholder: t('.placeholder') %>
    <div class="input-group-append">
      <%= f.submit t('.search'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/boards/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(board_id: board.id)),
            id: "js-bookmark-button-for-board-#{board.id}",
            class: 'float-right',
            method: :delete,
            remote: true do %>
  <%= icon 'fas', 'star' %>
<% end %>

app/views/boards/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <%= render 'search_form', url: bookmarks_boards_path %>
    </div>
  </div>
  <!-- 掲示板一覧 -->
<div class="row">
  <div class="col-12">
    <div class="row">
      <% if @bookmark_boards.present? %>
          <%= render @bookmark_boards %>
        <% else %>
          <%= t('.no_bookmark') %>
        <% end %>
      </div>
      <%= paginate @bookmark_boards %>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<%= render partial: 'form', locals: { submit_button: t('.submit')} %>

app/views/boards/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <%= render 'search_form', url: boards_path %>
      </form>
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <%= t('.no_board') %>
        <% end %>
      </div>
      <%= paginate @boards %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<%= render partial: 'form', locals: { submit_button: t('.submit')} %>


app/views/boards/show.html.erb
<% content_for(:title, @board.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%=image_tag @board.board_image.url, class: 'card-img-top img-fluid', size: '200×300' %>
            </div>
            <div class='col-md-9'>
              <h3 style='display: inline;'><%= @board.title %></h3>
              <ul class="list-inline">
                <li class="list-inline-item"><%= "by #{@board.user.decorate.full_name}"%></li>
                <li class="list-inline-item"><%= l @board.created_at, format: :long %></li>
              </ul>
            </div>
          </div>
          <p><%= @board.body %></p>
        </div>
      </article>
    </div>
  </div>
  <%= render partial: 'comments/form', locals: { board: @board, comment: @comment } %>
  <%= render partial: 'comments/comments', locals: { comments: @comments} %>
</div>