config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root to: 'static_pages#top'
  resources :users, only: %i[new create]
  resources :boards do
    resources :comments, shallow: true
    get 'bookmarks', on: :collection
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  namespace :admin do
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    post 'logout', to: 'user_sessions#destroy'
    get 'starter', to: 'dashboards#index', as: :root
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  skip_before_action :require_login
  layout 'admin_login'
  def new
    redirect_to root_path, warning: '権限がありません' if current_user&.general?
  end

  def create
    @user = login(params[:email], params[:password])
    if @user&.admin?
      redirect_to admin_root_path, success: t('.success')
    else
      redirect_to admin_login_path, danger: t('.warning')
    end
  end

  def destroy
    @user = logout
    redirect_to admin_login_path, success: t('.success')
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to boards_path, success: t('.success')
    else
      flash[:danger] = t('.failed')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.logout')
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<%= form_with url: login_path, method: :post, local: true do |f| %>
  <div class="container">
    <div class="row">
      <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <h1><%= t('.title') %></h1>
          <div class="form-group">
            <%= f.label :email, t('.email') %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
            <div class="form-group">
            <%= f.label :password, t('.password') %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <%= f.submit 'ログイン', class: 'btn btn-primary' %>
        <div class='text-center'>
          <a href="/users/new"><%= t('.sign_up') %></a>
          <%= link_to t('.forget_password'), new_password_reset_path %>
        </div>
      </div>
    </div>
  </div>
<% end %>